# Generated by Django 5.1 on 2024-08-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelTable(
            name='note',
            table=None,
        ),
    ]
